const swaggerJsdoc = require('swagger-jsdoc')

const options = {
  swaggerDefinition: {
    info: {
      title: 'Node.js API',
      description: 'Test API with autogenerated swagger doc',
      swagger: '2.0',
      version: '1.0.0',
      servers: ["http://localhost:3000"]
    },
  },
  apis: ['app.js', './routes/*.js', '.*.js'], // List of files to be processed.
  // You can also set globs for your apis
  // e.g. './routes/*.js'
}

const swaggerDoc = swaggerJsdoc(options)

module.exports = swaggerDoc
